### ISSUE TITLE
SRA links for data access

### ISSUE THREAD

**Issue by arq5x** [shishenyxx/Sperm_control_cohort_mosaicism#1]
Congrats on a very nice study. I am trying to access the raw data but cannot find any active SRA links. Could you let me know what I am doing wrong by pointing to an accession from which the BAM or FASTQ files for a given sample can be accessed? Thank you and apologies if I am missing something obvious.

**Comment by shishenyxx** [comment]
Hi Aaron,

Thank you for your interest in our study!

In the introduction of the repository, we listed "This repository collects pipelines, codes, and some intermediate results for the study of mosaic SNV/Indels for sperm, blood, and other samples of a control cohort. Raw data of this study is available on SRA under [PRJNA660493](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA660493/) and [PRJNA588332](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA588332/)." Also in the method part of the pdf of the paper you can find the raw data.

Xiaoxu

**Comment by arq5x** [comment]
Yes, I saw that. I followed the links to here, for example.  Unlike prior experience with SRA, I cannot find the links to programmatically download: https://www.ncbi.nlm.nih.gov/biosample/15951135

**Comment by shishenyxx** [comment]
Hi Aaron it's weird, because I can definitely see them from my side. 
![SRA_accession_page](https://user-images.githubusercontent.com/17311837/130508858-905586e9-54ad-4d32-bd15-9f447c63747c.png). Maybe it's because of the new login requirement from NCBI? Alternatively, we can share with you directly our processed bams from our side.

**Comment by arq5x** [comment]
Hmm, not sure. Can you send the URL that conveys that page?

**Comment by arq5x** [comment]
For me, it seems SRA links are available for PRJNA588332 but not PRJNA660493.

**Comment by arq5x** [comment]
![image](https://user-images.githubusercontent.com/72291/130517732-e97d7aa6-92ab-42e4-ad13-3ab6343e1160.png)
versus
![image](https://user-images.githubusercontent.com/72291/130517792-c8923466-83e6-4caa-91c5-da9978a471cd.png)

**Comment by shishenyxx** [comment]
Hi Aaron,

After I login I went to https://dataview.ncbi.nlm.nih.gov/object/PRJNA660493 and I can see them public. I already sent an email to SRA support team to see whether it's something on their side. For PRJNA588332 I saw exactly the same thing because I uploaded both of them ... Not sure whether it is because the new data are not completely processed. Also as Joe mentioned in his email, we are very happy to share our data directly from our server.

![图片](https://user-images.githubusercontent.com/17311837/130527177-5ef8f546-eacc-4d7e-9637-24ab5148d6c8.png)

Xiaoxu

**Comment by arq5x** [comment]
Thank you for your help and diligence!

**Comment by shishenyxx** [comment]
Hi Aaron,

From SRA it seems that even without login, the SRA run selecteor https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA660493&o=acc_s%3Aa should show something. Also contacting our server manager to see whether it is easier for us to open a guest account from our side.
![图片](https://user-images.githubusercontent.com/17311837/130670191-faa47133-3432-4d45-a009-aaba66eed575.png)

Xiaoxu
